name: elessam_law
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  odoo_rpc: 0.5.1
  flutter_chat_ui: 1.5.8
  firebase_messaging: 11.4.1
  flutter: 
    sdk: flutter
  firebase_core: ^1.17.1
  overlay_support: ^2.0.1
  get_storage: ^2.0.3
  flutter_launcher_icons: ^0.9.3

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter_icons:
  android: ic_launcher
  ios: true
  image_path: "assets/images/law3.png"
  adaptive_icon_background: "#ffffff"
flutter: 
  assets: 
    - assets/images/
  fonts: 
    - family: cairo
      fonts: 
        - asset: assets/font/cairo.ttf
  uses-material-design: true

